### ISSUE TITLE
Malformatted URL for API Client

### ISSUE THREAD

**Issue by bdcorps** [umami-software/api-client#3]
The API endpoint in the docs should not have a slash at the end. 

```
UMAMI_API_CLIENT_ENDPOINT=https://api.umami.is/v1/
```

should be 

```
UMAMI_API_CLIENT_ENDPOINT=https://api.umami.is/v1
``` 

![image](https://github.com/umami-software/api-client/assets/6132555/faba99a1-473a-44c0-b8bb-fba61625a071)

**Comment by uncenter** [comment]
This is related to the API client but should probably be an issue on the actual website repo: https://github.com/umami-software/website.

**Comment by mikecao** [comment]
Thanks, this has been fixed.
