### ISSUE TITLE
ENV vars not consistant with main doc

### ISSUE THREAD

**Issue by DMaxence** [umami-software/api-client#9]
In the doc https://umami.is/docs/api-client the `userId` var is called `UMAMI_API_CLIENT_USER_ID` when it's `UMAMI_API_USER_ID` in the code

<img width="973" alt="Capture d’écran 2023-12-07 à 17 01 39" src="https://github.com/umami-software/api-client/assets/23030942/18b2ac0d-0d50-4ab8-99a2-47a9b3ca3ad5">

https://github.com/umami-software/api-client/blob/2a4ffd43f4df1b73db06d08100616ff420a194e2/src/client.ts#L10

Linked with https://github.com/umami-software/api-client/pull/10

**Comment by hassan-jahan** [comment]
The problem still exists in v0.67.0
